---
title: "Final Project"
author: "Matti Harrison"
date: "11/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fs)
library(tidytext)
library(janitor)
library(leaflet)
library(ggmap)
library(zipcode)
library(maps)
library(viridis)
library(ggthemes)
```

##Reading in Data from Data.gov and Zillow
```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
##LA census data
la <- read_csv("2010_Census_Populations_by_Zip_Code.csv") %>% 
  clean_names() %>% 
  filter(total_population > 0) 
  
names(la)[names(la)=="zip_code"] <- "zipcode"

##LA Zillow data 
zipcodes_la <- read_csv("Zip_Zhvi_SingleFamilyResidence.csv") %>% 
  select(RegionName, "2010-12") %>% 
  filter(RegionName >= 90001,
         RegionName <= 93591) %>% 
  mutate_at(c(1), as.numeric)

names(zipcodes_la)[names(zipcodes_la)=="RegionName"] <- "zipcode"

##CT census data
connecticut <- read_csv("2010_Census_Population_And_Housing_Units_By_Town.csv")

names(connecticut)[names(connecticut)=="Municipality"] <- "City"

##CT Zillow data 
city_ct <- read_csv("City_Zhvi_SingleFamilyResidence.csv") %>% 
  select(RegionID, RegionName, State, CountyName, "2010-12") %>% 
  filter(State == "CT")

names(city_ct)[names(city_ct)=="RegionName"] <- "City"
```

##Bringing Data together
```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
losangeles <- left_join(la, zipcodes_la, by = "zipcode", copy = FALSE) %>% 
  drop_na("2010-12") %>% 
  mutate(state = "CA")

losangeles$zipcode <- as.character(losangeles$zipcode)

ct <- left_join(connecticut, city_ct, by = "City", copy = FALSE) %>% 
  drop_na("2010-12") %>% 
  mutate(state = "CT")

all <- full_join(losangeles, ct, by = "state") %>% 
  clean_names()

write_rds(all, path = "finalproject/la_ct.rds")
```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
##LA population
all %>% 
  ggplot(aes(x = zipcode, y = total_population)) + geom_col() + theme(axis.text.x = element_blank()) + 
  labs(title = "Populations in Specific LA areas", x = "", y = "Population")
#LA prices 
all %>%
  ggplot(aes(x = zipcode, y = x2010_12_x)) + geom_col() + theme(axis.text.x = element_blank()) + 
  labs(title = "Prices for Single Family Homes in LA", x = "", y = "Home Prices")

##CT population
all %>% 
  ggplot(aes(x = city, y = population)) + geom_col() + theme(axis.text.x = element_blank()) + 
  labs(title = "Populations in Connecticut cities", x = "", y = "Population")
#CT prices
all %>%
  ggplot(aes(x = city, y = x2010_12_y)) + geom_col() + theme(axis.text.x = element_blank()) + 
  labs(title = "Prices for Single Family Homes in CT", x = "", y = "Home Prices")

#Population and household size in LA, depending on age
##Population density for LA
all %>% 
  ggplot(aes(x = total_population, y = average_household_size, color = median_age)) + geom_point() + labs(title = "As the Population in an LA zipcode increases, the household size increases", subtitle = "As people get older they have a smaller household size", x = "Population per Zipcode", y = "Average Household Size", color = "Median Age per Zipode")

#Population and number of open houses, added pricing of homes
##does population correspond to more vacant homes
all %>%
  ggplot(aes(x = population, y = vacant_housing_units , color = x2010_12_y)) + geom_point() +
  labs(title = "As the population increases, the number of vacant homes increases in CT", 
       x = "Population", y = "Vacant Homes", color = "Home Prices")

#Population and home prices in LA, colored by average home size
all %>%
  ggplot(aes(x = total_population, y = x2010_12_x, color = average_household_size)) + 
  geom_point() +
  labs(title = "As population in LA zipcodes increase, the home prices decrease", 
       subtitle = "The most expensive homes have the smallest household size.",
       x = "Population", y = "Home Prices", color = "Average household size")

#Population and home prices in CT, colored by total number of homes
all %>%
  ggplot(aes(x = population, y = x2010_12_y, color = total_housing_units)) + geom_point() +
  labs(title = "As population in CT towns increases, the home prices decrease",
       subtitle = "As population increases the total number of available homes increases",
       x = "Population", y = "Home Prices", color = "Total houses")

```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
leaflet(options = 
            leafletOptions(dragging = FALSE,
                           minZoom = 6, 
                           maxZoom = 12))  %>% 
     addProviderTiles("CartoDB")  %>% 
     setView(lng = -118.2437, lat = 34.0522, zoom = 9)
```


